[Unit]
Wants=iccp-ros-monitor.service
After=iccp-ros-monitor.service

[Service]
Nice=10
CPUWeight=20
CPUQuota=100%
TasksMax=192
MemoryAccounting=yes
MemoryHigh=384M
MemoryMax=512M
KillMode=control-group
TimeoutStopSec=10s
SendSIGKILL=yes
