# Local NTP client configuration for tracer robots and mapping workstation.
server 192.168.50.42 iburst prefer minpoll 4 maxpoll 6

driftfile /var/lib/chrony/chrony.drift
makestep 1.0 -1
rtcsync

keyfile /etc/chrony/chrony.keys
leapsectz right/UTC
logdir /var/log/chrony
